homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Amsterdam
  customize:
    light.buitenlamp_achter_garage:
      homebridge_visible: true
      homebridge_name: Buitenlamp achter garage
    light.lamp_zithoek:
      homebridge_visible: true
      homebridge_name: Lamp zithoek
    group.kerstlampjes:
      homebridge_visible: true
      homebridge_name: Kerstlampjes
    switch.kaku_1:
      friendly_name: Kerstlampjes Heg (KaKu 1)
    switch.kaku_3:
      friendly_name: Kerstboom (KaKu 3)
      icon: mdi:pine-tree
      homebridge_visible: true
      homebridge_name: Kerstboom

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret http_password
  # Uncomment this if you are using SSL or running in Docker etc
  #base_url: example.duckdns.org:8123
  trusted_networks:
    - 127.0.0.1
    - ::1
    - 192.168.88.0/24

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Weather Prediction
sensor:
  platform: yr
  monitored_conditions:
    - temperature
    - symbol
    - windSpeed
    - cloudiness

# Text to speech
tts:
  platform: google

mqtt:
  broker: !secret mqtt_broker
  port: 1883
  client_id: home-assistant-1
  keepalive: 60
 
rfxtrx:
  device: /dev/rfxcom

light:
- platform: rfxtrx
  devices:
    0b110000011630be07010f70:
      name: Lamp zithoek
    0b110007011630be08010f70:
      name: Buitenlamp achter garage

- platform: mqtt
  name: "Lampen eettafel"
  command_topic: "cmnd/sonoff_eettafel/POWER"
  state_topic: "stat/sonoff_eettafel/POWER"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  retain: false

- platform: mqtt
  name: "Tuinlampen schuur"
  command_topic: "cmnd/sonoff_schuurlampen/POWER"
  state_topic: "stat/sonoff_schuurlampen/POWER"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  retain: false

switch:
  platform: rfxtrx
  automatic_add: False
  devices:        
    091300018898b2012c00:
      name: Sonoff RF
    0b110007011630be01010f70:
      name: KaKu 1
    0b110007011630be02010f70:
      name: KaKu 2
    0b110007011630be03010f70:
      name: KaKu 3
    0b110007011630be04010f70:
      name: KaKu 4
    0b110007011630be05010f70:
      name: KaKu 5
    0b110007011630be06010f70:
      name: KaKu 6
    0710010941010140:
      name: KaKu A1
    0710010941020140:
      name: KaKu A2
    0710010941030140:
      name: KaKu A3

camera:
  - platform: generic
    name: Voorkant
    still_image_url: !secret foscamc1_genericurl
    #ip: !secret foscamc1_ip
    #username: !secret foscamc1_username
    #password: !secret foscamc1_password
      
input_boolean:
  on_vacation:
    name: On vacation
    initial: off
    icon: mdi:tent

group: !include groups.yaml
automation: !include_dir_merge_list automation
