- alias: Buitenlamp voordeur aan bij zonsondergang
  hide_entity: False
  trigger:
    platform: sun
    event: sunset
  action:
    service: light.turn_on
    entity_id: light.buitenlamp_voordeur

- alias: Buitenlamp voordeur uit bij zonsopkomst
  hide_entity: False
  trigger:
    platform: sun
    event: sunrise
  action:
    service: light.turn_off
    entity_id: light.buitenlamp_voordeur
